# -*- coding: utf-8 -*-
"""Day 72

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rw5Q6FbBVXFQO9W4SVciNwBUtutS865s
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary'].max()
clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df.loc[43]

clean_df['Mid-Career Median Salary'].idxmax()

print(f"The max mid career salary: {clean_df['Mid-Career Median Salary'].loc[8]}$ for the major {clean_df['Undergraduate Major'].loc[8]}")

clean_df['Starting Median Salary'].idxmin()

print(f"The min starting median salary: {clean_df['Starting Median Salary'].loc[49]}$ for the major {clean_df['Undergraduate Major'].loc[49]}")

clean_df['Mid-Career Median Salary'].idxmin()

print(f"The min mid career salary: {clean_df['Mid-Career Median Salary'].loc[18]}$ for the major {clean_df['Undergraduate Major'].loc[18]}")

clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

clean_df.groupby('Group').count()

pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby("Group").mean(numeric_only=True)

